# Generated by Django 2.2.5 on 2019-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
