# Generated by Django 2.2.5 on 2019-11-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0002_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_seat', models.CharField(max_length=3)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mrbs.Day')),
            ],
        ),
    ]
