# Generated by Django 2.2.5 on 2019-11-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0004_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
