# Generated by Django 2.2.5 on 2019-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0005_auto_20191127_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
