# Generated by Django 2.2.5 on 2019-11-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0003_auto_20191127_1721'),
        ('app_mrbs', '0006_timeslot_status'),
    ]

    operations = [
    ]
