# Generated by Django 2.2.5 on 2019-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0007_merge_20191128_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='status',
            new_name='status1',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='user',
            new_name='user1',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status10',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status11',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status12',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status13',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status14',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status15',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status16',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status2',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status3',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status4',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status5',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status6',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status7',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status8',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status9',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user10',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user11',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user12',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user13',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user14',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user15',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user16',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user2',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user3',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user4',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user5',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user6',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user7',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user8',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user9',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
