# Generated by Django 2.2.5 on 2019-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0008_auto_20191128_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='of_room',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
