# Generated by Django 2.2.5 on 2019-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0009_timeslot_of_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='empty', max_length=100)),
                ('user', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
