# Generated by Django 2.2.5 on 2019-11-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0010_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='room',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='toslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_mrbs.Slot'),
            preserve_default=False,
        ),
    ]
