# Generated by Django 2.2.5 on 2019-11-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0015_auto_20191129_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='of_room',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_mrbs.Day'),
            preserve_default=False,
        ),
    ]
