# Generated by Django 2.2.5 on 2019-11-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0016_auto_20191130_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='room',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='roomday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_mrbs.RoomDay'),
            preserve_default=False,
        ),
    ]
