# Generated by Django 2.2.5 on 2019-11-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mrbs', '0017_auto_20191130_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
